### ISSUE TITLE
I'm not able to find the right distribution and packages that will make all xmp-tests run Ok on Python2.7

### ISSUE THREAD

**Issue by rmast** [jwilk/didjvu#22]
During the migration to Python3.10 I have no clue what those XMP-functionalities do. I saw Jakub to recently fix some tests for one of the XMP-possibilities, but my install just complains about some modules not installed.

What XMP-possibilities should be availabe in a new Python3.10 version, and with what Linux distribution and installing what packages/steps can I see the original tests complete with Python2.7?

**Comment by FriedrichFroebel** [comment]
According to the README:

1. [GExiv2](https://wiki.gnome.org/Projects/gexiv2) (≥ 0.10.3) + [PyGI](https://wiki.gnome.org/Projects/PyGObject) or
2. [python-xmp-toolkit](https://github.com/python-xmp-toolkit/python-xmp-toolkit) or
3. [pyexiv2](https://launchpad.net/pyexiv2) (≥ 0.3)

Judging from the CI definition, this should be satisfied using the following commands:

1. `sudo apt-get install python-gi gir1.2-gexiv2-0.10`
2. `sudo apt-get install libexempi[38] && python -m pip install python-xmp-toolkit`, see https://python-xmp-toolkit.readthedocs.io/en/latest/installation.html as well.
3. `sudo apt-get install libboost-python-dev libexiv2-dev && python -m pip install --verbose git+https://github.com/escaped/pyexiv2`.

**Comment by jwilk** [comment]
The packages mentioned by README and by @FriedrichFroebel are needed to run didjvu.
Apart from that, the tests themselves use python-xml-toolkit (regardless of which backend is being tested) and the Exiv2 command line tool (`sudo apt-get install exiv2`).

**Comment by rmast** [comment]
I now have _Ubuntu 18.04_ and these packages:
[packages.txt](https://github.com/jwilk/didjvu/files/8032573/packages.txt)

I get these messages/errors:

[messages.txt](https://github.com/jwilk/didjvu/files/8032586/messages.txt)

What do I miss?

**Comment by rmast** [comment]
I now also installed exiv2.

I now have these packages:
[packages.txt](https://github.com/jwilk/didjvu/files/8032606/packages.txt)

And I get these messages:

[messages.txt](https://github.com/jwilk/didjvu/files/8032608/messages.txt)


What am I missing.

**Comment by jwilk** [comment]
I couldn't get the pyexiv2 backend work on CI:

* on Ubuntu 18.04, the tests fail, presumably because of <https://dev.exiv2.org/issues/1112>;
* it fails to build on Ubuntu 20.04.

To be fair, I didn't try very hard; but I doubt there any users of that backend left. It's probably time to drop it.
[pyexiv2 has been deprecated upstream for nearly a decade](https://bugs.launchpad.net/pyexiv2/+bug/1074028).

**Comment by jwilk** [comment]
The GExiv2 backend is what's work best.
The reason the other backends exist is that when that code was added back in 2015, some distros I wanted to support didn't have a sufficiently new version of GExiv2.

**Comment by rmast** [comment]
Ok, the test_xmp run fine now on Python2.7, except for the mentioned pyexiv2:

tests.test_xmp.test_metadata.test_empty(gexiv2_backend, exiv2_checker) ... ok
tests.test_xmp.test_metadata.test_empty(gexiv2_backend, libxmp_checker) ... ok
tests.test_xmp.test_metadata.test_empty(libxmp_backend, exiv2_checker) ... ok
tests.test_xmp.test_metadata.test_empty(libxmp_backend, libxmp_checker) ... ok
tests.test_xmp.test_metadata.test_empty(pyexiv2_backend, exiv2_checker) ... ok
tests.test_xmp.test_metadata.test_empty(pyexiv2_backend, libxmp_checker) ... ok
tests.test_xmp.test_metadata.test_io_error(gexiv2_backend,) ... ok
tests.test_xmp.test_metadata.test_io_error(libxmp_backend,) ... ok
tests.test_xmp.test_metadata.test_io_error(pyexiv2_backend,) ... ok
tests.test_xmp.test_metadata.test_new(gexiv2_backend, exiv2_checker) ... ok
tests.test_xmp.test_metadata.test_new(gexiv2_backend, libxmp_checker) ... ok
tests.test_xmp.test_metadata.test_new(libxmp_backend, exiv2_checker) ... ok
tests.test_xmp.test_metadata.test_new(libxmp_backend, libxmp_checker) ... ok
tests.test_xmp.test_metadata.test_new(pyexiv2_backend, exiv2_checker) ... FAIL
tests.test_xmp.test_metadata.test_new(pyexiv2_backend, libxmp_checker) ... FAIL
tests.test_xmp.test_metadata.test_updated(gexiv2_backend, exiv2_checker) ... ok
tests.test_xmp.test_metadata.test_updated(gexiv2_backend, libxmp_checker) ... ok
tests.test_xmp.test_metadata.test_updated(libxmp_backend, exiv2_checker) ... ok
tests.test_xmp.test_metadata.test_updated(libxmp_backend, libxmp_checker) ... ok
tests.test_xmp.test_metadata.test_updated(pyexiv2_backend, exiv2_checker) ... FAIL
tests.test_xmp.test_metadata.test_updated(pyexiv2_backend, libxmp_checker) ... FAIL

I had to pip install pillow over python-pil.

**Comment by rmast** [comment]
> To be fair, I didn't try very hard; but I doubt there any users of that backend left. It's probably time to drop it. [pyexiv2 has been deprecated upstream for nearly a decade](https://bugs.launchpad.net/pyexiv2/+bug/1074028).

There appears to be a successor: https://python3-exiv2.readthedocs.io/en/latest/

Don't know if it's worth migration though.
